version: "3"

services:
  app-keycloak:
    # image: jboss/keycloak:latest  # para amd64
    # image: tiassiisspal/keycloak  # para mac m1 ou arm64
    image: jboss/keycloak:15.1.1  # para amd64
    #image: tiassiisspal/amd64-keycloak     # para amd54
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/h2:/home/keycloak/h2

  app-nest:
    build: ./nest/
    entrypoint: dockerize -wait tcp://db-nest:3306 -timeout 40s ./entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./nest/:/home/node/app
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - db-nest
      - app-keycloak

  db-nest:
    build: ./nest/.docker/mysql
    restart: always
    tty: true
    volumes:
      - ./nest/.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - app-keycloak
# //etc/hosts 
# //C:\Windows\system32\drivers\etc\hosts
# 127.0.0.1 host.docker.internal
  app-nextjs:
      build: ./next.js/ 
      entrypoint: ./entrypoint.sh
      ports:
        - 3001:3000
      volumes:
        - ./next.js/:/home/node/app
      extra_hosts: 
        - "host.docker.internal:172.17.0.1"
      depends_on:
        - app-keycloak
        - app-nest
        - db-nest
