version: "3"

services:
  app:
    # image: jboss/keycloak:latest  # para amd64
    # image: jboss/keycloak:15.1.1  # para amd64
    image: tiassiisspal/keycloak  # para mac m1 ou arm64
    # image: tiassiisspal/amd64-keycloak     # para amd54
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 8080:8080